Improve getting started
hermitcore-org/homepage pull request #4
Opened 2019-05-20 14:16 UTC by Harry-R

Various improvements regarding getting-started page:
* fix typo
* fix (outdated) links and folder names
* add install command for requirements
* remove "local-cmake" part, because `We require a fairly recent version of CMake (`3.7`) which is not yet present in most Linux distributions.` is not correct anymore. Current version in apt is 3.10.2, therefor cmake version from standard repositories should be used.

2019-05-20 14:20 UTC, Harry-R commented
If this request gets approved, I will update the other hermit repositories' readme files in accordance.

2019-05-28 09:07 UTC, jounathaen requested changes
I agree that this is not the perfect place for this information and that the custom cmake is a workaround. But I do not agree with simply deleting the whole information.

2019-05-28 09:08 UTC, jounathaen commented
Thanks for your effort. Except of the cmake part it looks very good  :+1: . Maybe you have some time to adapt it

2019-06-18 18:58 UTC, Harry-R commented
@jounathaen sorry for the late answer.

How should I deal with the cmake part instead of deleting it?
What about moving it to a 'notes' section at the end of the installation instruction?

2019-09-09 21:03 UTC, stlankes commented
@jounathaen @Harry-R Excuse me for the late response. I would also delete the cmake part. It is obsolete. Which note section do you mean?

2025-02-02 13:28 UTC, closed without merging